### ISSUE TITLE
TypeError When Searching

### ISSUE THREAD

**Issue by branttaylor** [gilbitron/Raneto#307]
New install of Raneto using the Docker image. When I attempt to search, I get this error message:

```
TypeError: Cannot read property 'forEach' of undefined
    at getLunr (/opt/raneto/app/core/search.js:17:33)
    at handler (/opt/raneto/app/core/search.js:40:24)
    at /opt/raneto/app/routes/search.route.js:28:26
    at Layer.handle [as handle_request] (/opt/raneto/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/raneto/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/raneto/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/raneto/node_modules/express/lib/router/layer.js:95:5)
    at /opt/raneto/node_modules/express/lib/router/index.js:281:22
    at param (/opt/raneto/node_modules/express/lib/router/index.js:354:14)
    at param (/opt/raneto/node_modules/express/lib/router/index.js:365:14)
```

Config Files

server.js
```
    #!/usr/bin/env node

    'use strict';

    // Modules
    var raneto = require('/opt/raneto/app/index.js');
    var config = require('/opt/raneto/example/config.default.js');
    var app = raneto(config);
    var server = app.listen(app.get('port'), function () {});
```

config.default.js
```
    'use strict';

    // Modules
    var path = require('path');

    var config = {
      site_title: 'Platforms Documentation',
      base_url: 'https://wiki.naskube.stage.lifeway.com',
      support_email: 'cloudops@lifeway.com',
      copyright: 'Copyright LifeWay IT &copy; ' + new Date().getFullYear() + ' - <a href="http://raneto.com">Powered by Raneto</a>',
      excerpt_length: 400,
      page_sort_meta: 'sort',
      category_sort: true,
      show_on_home_default: true,
      theme_dir  : '/opt/raneto/themes/',
      theme_name : 'default',
      content_dir : '/data/content/',
      // Where is the public directory or document root?
      public_dir  : path.join(__dirname, '..', 'themes', 'default', 'public'),
      // The base URL of your images folder,
      // Relative to config.public_dir
      // (can use %image_url% in Markdown files)
      image_url: '/data/images',
      allow_editing : false,
      authentication : false,
      authentication_for_edit: false,
      authentication_for_read: false,
      // Google OAuth
      googleoauth: false,
      oauth2 : {
        client_id: '0oaby1626rMUccL091t7',
        client_secret: '-GI0dE92n58QW8kFvh143XsLgAl0N_z0kFQv9Iwj',
        callback: 'https://wiki.naskube.stage.lifeway.com/okta/callback',
        hostedDomain: 'okta'
      },
      secret: '2n58QW8kFvh143XsL',
      locale: 'en',
      datetime_format: 'Do MMM YYYY',
      rtl_layout: false,
      home_meta : {
        // title       : 'Custom Home Title',
        // description : 'Custom Home Description'
      },
      table_of_contents: false
    };
    config.public_dir = '/opt/raneto/themes/default/public';

    // Exports
    module.exports = config;
```

**Comment by ryanlelek** [comment]
Hi @branttaylor 
Did this get resolved?

Please try in v0.17.1 as lots has changed.

This could be related to you specifying absolute paths and Raneto is unable to find any pages to search.
Marking this as bug for now
